=== Bhalajikharthik/EventGrande/book.dtd
<!ELEMENT book (name,email,phone,etype,people,budget,location,details)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST book name ID CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ATTLIST book email ID CDATA #REQUIRED>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST book phone ID #REQUIRED>
<!ELEMENT etype (#PCDATA)>
<!ATTLIST book etype CDATA #REQUIRED>
<!ELEMENT people (#PCDATA)>
<!ATTLIST book people CDATA #REQUIRED>
<!ELEMENT budget (#PCDATA)>
<!ATTLIST book budget CDATA #REQUIRED>
<!ELEMENT location (#PCDATA)>
<!ATTLIST book location CDATA #REQUIRED>
<!ELEMENT details (#PCDATA)>
<!ATTLIST book details ID CDATA #REQUIRED>

=== Bhalajikharthik/EventGrande/book.xml
<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
    <name>Bhalaji Kharthik</name>
    <email>bhalajikharthik3004@gmail.com</email>
    <phone>9585035446</phone>
    <etype>College Event</etype>
    <people>300</people>
    <budget>80000</budget>
    <location>Coimbatore</location>
    <details type="text">sample description</details>
</book>
